### ISSUE TITLE
花火大會的元件都會被框到

### ISSUE THREAD

**Issue by zx123497** [zx123497/zx123497.github.io#1]
![image](https://user-images.githubusercontent.com/43847473/135894112-c0fc5fac-36f6-4a7f-a5e8-da0e926af79a.png)
長這樣!!

**Comment by Feilian1999** [comment]
FQ

**Comment by Feilian1999** [comment]
root cause: CSS setting problem
solution: set WebkitUserSelect and WebkitUserDrag to None
commit: https://github.com/zx123497/zx123497.github.io/commit/6912f5e98a514109c8ddca0a483cf3e40863981d
