### ISSUE TITLE
加入會場畫面的加入按鈕很醜

### ISSUE THREAD

**Issue by zx123497** [zx123497/zx123497.github.io#2]
![image](https://user-images.githubusercontent.com/43847473/135895052-7613bb7b-0736-4423-b010-b9c02f4281d0.png)
請重新設計按鈕

**Comment by Feilian1999** [comment]
Root Problem: text didn't set to center
Solution: set text-align to center
Commit: https://github.com/zx123497/zx123497.github.io/commit/6912f5e98a514109c8ddca0a483cf3e40863981d
